import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* top nav bar */}
        <nav className="fixed top-0 left-0 w-full bg-white dark:bg-gray-900 shadow-md z-50 px-64 py-2 flex justify-between items-center">
          {/* Logo */}
          <h1 className="text-2xl font-bold">EVE</h1>

          {/* Navigation Links */}
          <div className="flex space-x-8">
            <a href="#" className="font-semibold text-gray-700 hover:text-black">Home</a>
            <a href="#" className="font-semibold text-gray-700 hover:text-black">Blog</a>
            <a href="#" className="font-semibold text-gray-700 hover:text-black">Project</a>
            <a href="#" className="font-semibold text-gray-700 hover:text-black">Contact</a>
          </div>
        </nav>


        {/* mian contant */}
        <main>{children}</main>
      </body>
    </html>
  );
}