import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* top nav bar */}
        <nav className="flex justify-between items-center px-40 py-2 shadow-md border">
          {/* Logo */}
          {/* <Image src="/images/profile.jpg" alt="avatar" width={50} height={50} className="rounded-full w-12 h-12"/> */}
          <a className="text-gray-700 font-bold text-2xl"> EVE </a>
          {/* link to other page */}
          <div className="space-x-6">
            <Link href="/" className="text-gray-700 font-semibold text-lg hover:text-black">Home</Link>
            <Link href="/blog" className="text-gray-700 font-semibold text-lg hover:text-black">Blog</Link>
            <Link href="/project" className="text-gray-700 font-semibold text-lg hover:text-black">Project</Link>
            <Link href="/contact" className="text-gray-700 font-semibold  text-lg hover:text-black">Contact</Link>
          </div>
        </nav>

        {/* mian contant */}
        <main>{children}</main>
      </body>
    </html>
  );
}